# Generated by Django 3.1.3 on 2020-11-09 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('short_description', models.CharField(max_length=250, verbose_name='Copete')),
                ('large_description', models.TextField(max_length=4086, verbose_name='Descripcion')),
                ('url_name', models.CharField(max_length=120, verbose_name='Nombre_url')),
                ('url_base', models.CharField(max_length=120, verbose_name='Base_url')),
                ('url_player_sufix', models.CharField(max_length=120, verbose_name='Sufijo_url_player')),
                ('station_type', models.CharField(max_length=120, verbose_name='Sufijo_url_player')),
                ('transmission_start_time', models.TimeField()),
                ('transmission_end_time', models.TimeField()),
                ('live_stream_mp3_url', models.CharField(max_length=120, verbose_name='live_stream_mp3_url')),
                ('live_stream_AAC_url', models.CharField(max_length=120, verbose_name='live_stream_AAC_url')),
                ('use_external_stream', models.BooleanField(default=False)),
                ('external_stream_url', models.CharField(max_length=120, verbose_name='external_stream_url')),
                ('is_HD', models.BooleanField(default=True)),
                ('frequency', models.CharField(max_length=120, verbose_name='frequency')),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('station_site', models.CharField(max_length=50)),
                ('is_repeater', models.BooleanField(default=False)),
                ('repeated', models.CharField(max_length=50)),
                ('shown_repeaters_map', models.BooleanField(default=False)),
                ('grupo', models.CharField(max_length=100)),
                ('main_image', models.ImageField(default='station_images/default.png', upload_to='station_images')),
                ('secondary_image', models.ImageField(default='station_images/default.png', upload_to='station_images')),
                ('station_poster', models.ImageField(default='station_images/default.png', upload_to='station_images')),
                ('facebook_profile_image', models.ImageField(default='station_images/default.png', upload_to='station_images')),
                ('twitter_profile_image', models.ImageField(default='station_images/default.png', upload_to='station_images')),
                ('twitter_cover_image', models.ImageField(default='station_images/default.png', upload_to='station_images')),
                ('Instagram_profile_image', models.ImageField(default='station_images/default.png', upload_to='station_images')),
                ('HTML_color_code', models.CharField(max_length=50)),
                ('facebook_link', models.CharField(max_length=120, verbose_name='facebook_link')),
                ('instagram_link', models.CharField(max_length=120, verbose_name='instagram_link')),
                ('twitter_link', models.CharField(max_length=120, verbose_name='twitter_link')),
                ('facebook_invite_text', models.TextField(max_length=4086, verbose_name='facebook_invite_text')),
                ('twitter_invite_text', models.TextField(max_length=4086, verbose_name='twitter_invite_text')),
                ('seo_labels', models.CharField(max_length=256, verbose_name='seo_labels')),
                ('seo_title', models.CharField(max_length=256, verbose_name='seo_title')),
                ('seo_meta', models.TextField(max_length=4086, verbose_name='facebook_invite_text')),
            ],
        ),
    ]
