# Generated by Django 3.1.3 on 2020-11-10 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201109_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del grupo')),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='group',
        ),
        migrations.AddField(
            model_name='station',
            name='group',
            field=models.ManyToManyField(blank=True, to='api.Group', verbose_name='Tipo de estacion'),
        ),
    ]
